### PR TITLE
Add `x-pre-hashed` field during command initialisation

### PR DESCRIPTION
**Pull request by sysr-q**
This patch allows clients to store the SHA-256 hash of the password in their bloostamp file.
This doesn't really inherently make it a more secure system, but allows clients to **not** store a password, allowing user input when required (only during sending coins). This also means that users can use a password they can easily remember, perhaps saving the day.

The only drawback here is that this is still entirely vulnerable to a MITM attack, so SSL would have to be implemented.

Usage is simply as such:

``` json
{
    "cmd": "send_coin",
    "to": "FOO123456....",
    "addr": "HYPOTHETICAL_BLOOCOIN_ADDRESS",
    "pwd": "sha256123aef5A....", // clearly not real
    "x-pre-hashed": null
}
```

So this coupled with SSL could make bloostamps less like a "come and get me" and more just an easy way for clients to store relevant addresses.
After this, to keep semi-backwards compatibility (e.g. it won't break a client but transactions will fail), a new bloostamp could look like such: `HYPOTHETICAL_BLOOCOIN_ADDRESS::CLIENT_1` (an empty password block, and the client identifier at the end, which would be optional).

Discussions would be nice, I'm not 100% this is a decent addition, but in my mind it could clean up how clients interact with users. Definitely SSL would be required to really make this better.

### CODE REVIEW

**Comment by sysr-q** [comment]
An example implementation would be (hypothetically speaking):

``` python
with open(user.bloostamp, 'rb') as f:
    data = f.readline().split(':')
    pre_hashed = False
    addr = data[0]
    pwd = data[1]
    if len(pwd) == 0:
        pwd = hashlib.sha256(getpass.getpass()).hexdigest()
        pre_hashed = True
    out = {
        "cmd": "send_coin",
        "to": outbound,
        "addr": addr,
        "pwd": pwd,
    }
    if pre_hashed:
        out['x-pre-hashed'] = None
    req(out)
```

Clearly using `getpass.getpass()` over something like `raw_input()` so that the password isn't displayed in clear text on a terminal scrollback.

**Comment by sysr-q** [comment]
@Max00355 - opinions on this? If you implement something like this with SSL rather than just a plain socket, this could make stuff a tiny bit more secure.

**Comment by f-prime** [comment]
Would this make the current system stop working, or just depreciated?

**Comment by sysr-q** [comment]
That's the beauty of the implementation, it's just an `if 'x-pre-hashed in self.data`, so it's only used if the client sends it.
That means that the protocol isn't going to break anything.

**Pull request merged**
