### PR TITLE
JSON responses

### PR DESCRIPTION
**Pull request by sysr-q**
This significantly changes the way the server and clients will interact, so I'm interested in what everyone else thinks, before we consider a merge.
@Max00355, @jBrown91 - how would you guys feel about JSON going to and from the server? It makes it much easier to communicate, since most languages have easy ways to read and write JSON to sockets.

This implements the suggestions in #5, and more so the structure from there, meaning this:

``` python
{
    "success": bool,
    "message": None, # incase of errors,
    "payload": { # What the command returns (None if errors)
        "this": "that",
        "foo": "bar"
    }
}
```

So see what you guys think, there are still things which could be improved, but I think it's a nice change, and makes it easier for clients to communicate with the server.
If it's taken well, I'll probably write up some clean protocol documentation so developers can get into bloocoins easily.

### CODE REVIEW

**Comment by sysr-q** [comment]
There are still a few things that should be done before I consider this merge worthy:
- [x] Clean up the leftover code
- [ ] Implement some more little convenience things (like number of total coins, hashrate (if possible), and others)
- [x] Document the source
- [ ] Write a documentation of the protocols

**Comment by sysr-q** [comment]
If you want to, we can merge this now, and get people to work with it from now on.
Since replies are fairly standardized (e.g. everything is under `payload` if `success == True`), it shouldn't be hard for people to move over to the new system.

**Comment by f-prime** [comment]
Not yet, let me finish the client for this.

It seems as though there is a bug with validating users though. When creating the "my_coin" function I keep getting a success: false, but that's not the case. I don't have time to really look into it right now, but until everything is finished, and until we have a truly working client, I don't want to merge it. Would you agree?

**Comment by sysr-q** [comment]
That's fair enough. What are you sending and what are you receiving? I was fairly certain no problems should come up, but I might have missed something and that's leading to some problems.
More specifically, what's the message you get with no success? That should help us track down the bugs.

**Comment by f-prime** [comment]
I am sending receiving {"message": "Your address or password was invalid", "payload": null, "success": false}

And I am sending: {"cmd":"my_coins", "addr":addr, "pwd":key})

**Comment by sysr-q** [comment]
Did you forget to send a register command to the server, if you're running a test build?
That happens when your account doesn't show up in the database.

``` python
        # Here, specifically:
        if mongo.db.address.find_one({"addr": addr, "pwd": pwd}):
            coins = len(mongo.db.coins.find({"addr": addr}))
            self.success({"amount": coins})
            return
        else:
            self.error("Your address or password was invalid")
```

**Comment by sysr-q** [comment]
Oh jeez, looking at it now, it looks like I did `mongo.db.address`, rather than `mongo.db.addresses`, how embarrassing. Give me one moment to fix that in a commit.

**Comment by f-prime** [comment]
hahahahaha, woow ;P

**Comment by sysr-q** [comment]
So is this merge-worthy, in your eyes?
Right after we do this, we have to get a jump start on some decent cryptography, because as has been noted by the miners available, this isn't even remotely cryptographically strong. Not a single bit. Even if we made it so miners race for a coin, that would improve it. Seriously.

**Comment by f-prime** [comment]
Not until I finish the client, which shouldn't be too long.

And okay, but that makes every current coin have no value.

**Comment by f-prime** [comment]
What do you have in mind for making this more cryptographic? I mean, making every client fight for a specific coin is easy, just store the start string, but is that enough to call it cryptographic?

**Comment by sysr-q** [comment]
There are things we could do, I've been talking to a friend who's much better with cryptography than I am, but you know.
We'll talk more as a community some time when we're all free.

**Comment by f-prime** [comment]
All right, that sounds good

**Comment by f-prime** [comment]
See, these little bugs are the reason we can't merge it yet, I made a small fix, have a look at my_coins.py

You can not use len() on a pymongo .find() function.

**Comment by sysr-q** [comment]
I refuse to believe that, because I've tested most functions in the server and they work perfectly.
[This](http://stackoverflow.com/a/12764465) answer on SO proves my point, you can `.count()` to return an integer from the server's perspective, or you can `len()` the return to count the documents, since it's iterable.

**Comment by f-prime** [comment]
I really hope you are right because the way I am implementing this is sloppy. It's just, I was getting a Cursor error when I was trying to retrieve the coins from the server.

**Comment by f-prime** [comment]
Woo! I fixed it! Looking much nicer now correct? I did: coins = mongo.db.coins.find({"addr":addr}).count()

Now I don't feel like I wrote shit code any more :)

**Comment by sysr-q** [comment]
Yeah, that's a lot better. No point iterating if you don't have to.

**Comment by f-prime** [comment]
I know, believe me I don't like sloppy code either, it's just sometimes that's what I spit out. This is nice though. When I get home I will test everything else, fix the rest of the bugs (if they exist) and I will merge the changes.

For mining I was thinking for now we will just store the start_string in the database with the hash so that when the miner finds a solution it must also send the start string, this way it is a fight for the current coin and not just random hashes. Sound good?

**Pull request merged**
