### PR TITLE
Remove password requirement from my_coins command

### PR DESCRIPTION
**Pull request by ajvpot**
Removing the password requirement to check the account balance opens up
the ability for users to verify that other users actually have the money
they claim to have. This will not break compatibility with older
clients.

Note: The name of this command doesn't really make sense any more but I didn't change it for compatibility purposes.

### CODE REVIEW

**Comment by ajvpot** [comment]
Also don't let people send coins to themselves. I'm not quite sure how to make that a separate pull.

**Comment by sysr-q** [comment]
From what I've read in a few places, a few people use this command to verify if the given credentials are valid (e.g. on whatisnames web wallet).
A new command (something like `valid_credentials` or `valid_*` with something reasonable there) to verify if you're giving valid credentials would be **perfect**.

**Comment by f-prime** [comment]
It's a good idea, I will probably make a version of this on my own. I will probably add a command instead, such as check_addr which returns the info about that addr. This way, as you said, people can be confident about their transactions and what not. I will not be mergine your request though, just building off the idea. I appreciate it!

**Comment by sysr-q** [comment]
Why not merge it? This seems reasonable.

**Comment by ajvpot** [comment]
Resolved: added check_addr command with b8304374daecea9dab56fec97f5c2cda19f7a583

**Pull request closed without merging**
